site_name: Bitski Docs
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Authentication: oauth.md
  - Client Settings: client-settings.md
  - Sending Transactions: transactions.md
  - App Wallets: app-wallet.md
  - Backend Verification: backend_verification.md
  - Examples: examples.md
  - FAQ: faq.md
extra:
  sdks:
    - name: JavaScript
      url: https://github.com/BitskiCo/bitski-js/
    - name: Node.js
      url: https://github.com/BitskiCo/bitski-node/
    - name: iOS
      url: https://github.com/BitskiCo/bitski-ios/
    - name: Truffle
      url: https://github.com/BitskiCo/bitski-truffle-provider
  thirdparty:
    - name: 0xcert
      url: https://docs.0xcert.org/framework/v2/api/ethereum-connectors.html#bitski-back-end-provider
theme:
  name: null
  custom_dir: bitski_theme
plugins:
  - search
copyright: © 2019 Out There Labs, Inc.
extra_javascript:
