site_name: Bitski Docs
pages:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Authentication: oauth.md
  - Client Settings: client-settings.md
  - Sending Transactions: transactions.md
  - App Wallets: app-wallet.md
  - Examples: examples.md
  - FAQ: faq.md
extra:
  sdks:
    - name: JavaScript
      url: https://github.com/BitskiCo/bitski-js
    - name: iOS
      url: https://github.com/BitskiCo/bitski-ios
    - name: Truffle
      url: https://github.com/BitskiCo/bitski-truffle-provider
theme:
  name: null
  custom_dir: bitski_theme
plugins:
  - search
copyright: © 2018 Out There Labs, Inc.
extra_javascript:
